# Generated by Django 4.2.4 on 2023-08-30 16:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_sem2', '0003_alter_coin_kick_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='kick_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 30, 19, 59, 4, 824763)),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('public_date', models.DateTimeField(auto_now=True)),
                ('change_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp_sem2.author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp_sem2.post')),
            ],
        ),
    ]
