# Generated by Django 4.2.4 on 2023-08-30 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_sem2', '0004_alter_coin_kick_time_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='kick_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 30, 21, 34, 15, 590231)),
        ),
    ]
